{
 "title": "becycled",
 "time": { "from": "2021-06-18T22:06:24.088Z", "to": "2021-06-19T11:16:55.016Z" },
 "panels": [
  {
   "title": "Map",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 0 },
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT fix_time,\n       tracker_id,\n       speed,\n       latitude,\n       longitude\nFROM telemetries\nWHERE $__timeFilter(fix_time)\nGROUP BY fix_time, tracker_id\nORDER BY fix_time\nLIMIT 10000"
    }
   ]
  },
  {
   "title": "Speed by tracker",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT fix_time,\n       speed,\n       tracker_id\nFROM telemetries\nWHERE $__timeFilter(fix_time)\nGROUP BY fix_time, tracker_id\nORDER BY fix_time\nLIMIT 10000"
    }
   ]
  },
  {
   "title": "Max speed in 1 hour",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('hour', fix_time) as \"time\",\n  max(speed) as \"speed\"\nFROM telemetries\nWHERE\n  $__timeFilter(\"fix_time\")\nGROUP BY fix_time\nORDER BY fix_time\nLIMIT 100000"
    }
   ]
  }
 ]
}