---
- name: Install Docker dependencies
  apt:
    update_cache: true
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Add Docker GPG apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Add Docker repository
  apt_repository:
    repo: >-
      deb https://download.docker.com/linux/ubuntu
      {{ ansible_distribution_release | lower }}
      stable
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Install Docker
  apt:
    update_cache: true
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: yes
  when: ansible_distribution == 'Ubuntu'

- name: Install Docker-Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x'
  when: ansible_distribution == 'Ubuntu'
