---
- name: Install ufw
  apt:
    update_cache: yes
    name: ufw
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Allow SSH
  become: true
  ufw:
    rule: allow
    name: OpenSSH
  when: ansible_distribution == 'Ubuntu'

- name: Enable ufw
  ufw:
    state: enabled
  when: ansible_distribution == 'Ubuntu'
